### ISSUE TITLE
Ability to download by folder I.e. only shared

### ISSUE THREAD

**Issue by wkeull** [ndbroadbent/icloud_photos_downloader#100]
This is a great utility, is there a potential in the future where a certain folder/album can be specified for download vs the root folder/album of all images specifically the shared folder?

**Comment by ndbroadbent** [comment]
Hey that's a great idea! It would be great if we could include or exclude
certain albums. I don't have to time to work on it right now unfortunately,
but it's definitely something I would like to add in the future.

**Comment by menkej** [comment]
I think this is also implemented in #134 and can be closed @ndbroadbent

**Comment by ndbroadbent** [comment]
Thanks @menkej, will close!
