### ISSUE TITLE
`pyicloud-ipd` still imports from `pyicloud`?

### ISSUE THREAD

**Issue by drvdijk** [ndbroadbent/icloud_photos_downloader#101]
Very cool project this is! I was just playing around with it over the weekend in an effort to make some sense out of my photo workflow. The idea was to gather all "media input" (phone, camera, video cam, ...) in one place and go from there culling, retouching, creating albums, .... Well that project isn't done yet! ;)

Anyhow! :) I was trying to see if I could run a docker image with the latest version (`1.3.1`, did a `docker build -t drvdijk/icloudpd docker/` with updated version), without specifying passwords on the command line. So I tried running `icloud` from a terminal in the running container, but ...

```
docker exec -it icloudpd sh
/ $ icloud
Traceback (most recent call last):
  File "/usr/bin/icloud", line 7, in <module>
    from pyicloud_ipd.cmdline import main
  File "/usr/lib/python2.7/site-packages/pyicloud_ipd/cmdline.py", line 14, in <module>
    import pyicloud
ImportError: No module named pyicloud
/ $
```

The `pip list` gives:

```/ $ pip list
Package         Version
--------------- -------------------
certifi         2018.8.24
chardet         3.0.4
click           6.7
docopt          0.6.2
future          0.16.0
icloudpd        1.3.1
idna            2.6
keyring         8.7
keyrings.alt    1.3
piexif          1.0.13
pip             10.0.1
pyicloud-ipd    0.9.6
python-dateutil 2.6.1
pytz            2018.5
requests        2.18.4
schema          0.6.6
setuptools      39.1.0.post20180508
six             1.11.0
tqdm            4.14.0
tzlocal         1.5.1
urllib3         1.22
```

I think this issue relates to #85, where `pyicloud` was released as `pyicloud-ipd`. The code itself still imports from `pyicloud`, whereas on the system it's available as `pyicloud-ipd`.

Hope this is somewhat right (not done very much python work) and it helps :) Thanks again for this fun project!

**Comment by ndbroadbent** [comment]
Hello, sorry about that! I forgot to update the import in the `icloud` command-line tool. I have fixed this, released a new version, and updated the Docker image.
