### ISSUE TITLE
Continuous integration tests failing due to timestamp mismatch

### ISSUE THREAD

**Issue by kode54** [ndbroadbent/icloud_photos_downloader#118]
Your CI test script appears to be failing due to a timestamp mismatch, either due to wrong time zone setting for the test instance, or incorrect assumption about AM/PM time, as the timestamps actually differ by exactly 12 hours.

**Comment by ndbroadbent** [comment]
Thanks a lot for letting me know! I wasn't getting any build failure notifications from Travis CI. It's because I had changed my default git email address, but forgot to verify it in my GitHub account.

I'll get those tests fixed!

**Comment by ndbroadbent** [comment]
Fixed in 210d7124b24935080f210a6ec168c9ed07a81721.

Thanks again, haha I just realized that I haven't been getting Travis CI email notifications for the last 4 years. Nice to have those again
