### ISSUE TITLE
my docker image

### ISSUE THREAD

**Issue by zhfish** [ndbroadbent/icloud_photos_downloader#126]
https://hub.docker.com/r/zhfish/icloudpd

**Comment by ndbroadbent** [comment]
Hi, thanks for posting! What’s the difference between this Docker image and the one that we provide?

**Comment by zhfish** [comment]
1. add scheduled task
2. simpler to use

**Comment by ndbroadbent** [comment]
Oh nice, I saw you added some env variables to control the arguments. Good idea!

For anyone else, here's the [Dockerfile](https://github.com/zhfish/icloudpd/blob/master/Dockerfile). (Compared to our [Dockerfile](https://github.com/zhfish/icloudpd/blob/master/Dockerfile).)

Thanks for mentioning this! I don't know if everyone needs the cron schedule, but it's a good reference to have. Will close this issue for now, but people should still be able to find it with a Google search
