### ISSUE TITLE
Live photos not downloading

### ISSUE THREAD

**Issue by wshelley** [ndbroadbent/icloud_photos_downloader#14]
Live photos are not downloading, proabably an issue with pyicloud, can you suggest a fix?

Great project btw :+1:

**Comment by MaxPower9** [comment]
Yea, it would be nice to keep the live photos.  I did some testing, when I export a live photo out of photos.app on my mac to a folder, I get a picture and a .mov video file.  So I wonder if the downloader is able to download the .mov video too or not.

**Comment by ndbroadbent** [comment]
Hello, sorry this is happening! This project is just a small wrapper around the [pyicloud](https://github.com/picklepete/pyicloud) library, so it might be better to post an issue over there.
