### ISSUE TITLE
New Python User

### ISSUE THREAD

**Issue by RonSwanson299** [ndbroadbent/icloud_photos_downloader#143]
Hello, I am new to using Python for API services and would appreciate some help if anyone is willing to lend a hand.  I have been racking my brain on how to get this started, but I cant seem to be able to figure it out.  If someone would be willing to share their code, I would be very grateful. Im sure I am missing a few steps, but like I said I am very new to this. Thank you!

**Comment by metahnetoutage** [comment]
I was able to make it work. You want to know how to have this software work? Please elaborate precisely what is your question about and what do you not understand!

**Comment by menkej** [comment]
Hi @RonSwanson299 !
What exactly is your issue with iCloud_photosdownloader?

cheers
Jörg

**Comment by menkej** [comment]
as there was no reaction within almost 3 weeks I close this now. Feel free to reopen and update your description, if you think this is still valid, @RonSwanson299 Thanks.
