### ISSUE TITLE
Creating Docker Image

### ISSUE THREAD

**Issue by wes1993** [ndbroadbent/icloud_photos_downloader#147]
When i try to create a docker image i receive this error
No matching distribution found for icloudpd==

Thanks a lot
Stefano

**Comment by AndreyNikiforov** [comment]
Updated Dockerfile to build from local source (should work on Docker Hub autobuild too) and added doc on building docker locally: https://github.com/ndbroadbent/icloud_photos_downloader/pull/162

**Comment by AndreyNikiforov** [comment]
Latest from master should work as it grabs your local source. Official docker image has been updated to the latest too, so you can use that one now (amd64 only though). @wes1993 please report if your issue has been solved.

**Comment by wes1993** [comment]
Sorry I don’t use anymore this software (For Now)!! But thanks a lot for your reply :)
Regards
Stefano
