### ISSUE TITLE
Keep photos from last 30 days

### ISSUE THREAD

**Issue by konradorlinski** [ndbroadbent/icloud_photos_downloader#174]
Hi!
Is there any posibility to download all photos with delete option, but don't delete photos from 30 days or keep e.g. last 100 photos?

**Comment by menkej** [comment]
This is not implemented yet. I'm also a little concerned about deleting the users photos. Imagine you are just "playing around with options" and delete your pictures by accident... I would leave this feature out and let the user delete his pics himself if he/she wants to...

**Comment by konradorlinski** [comment]
Thanks for answer!
I propably wrong understood autodelete option. Now all is clear. Indeed, delete feature will be propably unsafe
