### ISSUE TITLE
Support for .mov

### ISSUE THREAD

**Issue by itadder** [ndbroadbent/icloud_photos_downloader#21]
I understand this is for photos, but would their also be a technical reason why Videos are not supported?
Could not process IMG_3278.MOV! Maybe try again later.

**Comment by ndbroadbent** [comment]
Hi, yes the script can download video files if you pass the `--download-videos` flag. The `Could not process` error is probably a bug or a limitation in the pyicloud library. Whenever Apple releases a new iOS update, they tend to move things around and break things.
