### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by tachyonxero** [ndbroadbent/icloud_photos_downloader#24]
Login and 2-Factor OK:

> Signing in...
> Updating photos...
> Traceback (most recent call last):
>   File "download_photos.py", line 231, in <module>
>     download()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "download_photos.py", line 55, in download
>     updatePhotos(icloud)
>   File "download_photos.py", line 155, in updatePhotos
>     icloud.photos.update()
>   File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 306, in photos
>     self.params
>   File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 35, in __init__
>     params=self.params
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
>     response = super(PyiCloudSession, self).request(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p10-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=93754147&clientId=0A0FB892-5738-11E7-9B6E-B827EBF49F22 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75a6a2d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
Not sure what went wrong. I am realitivily new to Linux and Github so if it's something simple I have not done I apologise in advance.

**Comment by jspraul** [comment]
Ubuntu 12.04.5 LTS, Python 2.7.3

Here is my call stack for the same error, but after several 110 timeout errors. Still nothing downloaded successfully yet.

```
Signing in...
Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by ndbroadbent** [comment]
Hello, sorry this is happening! This project is just a small wrapper around the [pyicloud](https://github.com/picklepete/pyicloud) library, so it might be better to post an issue over there.
