### ISSUE TITLE
2fa after each reboot?

### ISSUE THREAD

**Issue by rbmagnus** [ndbroadbent/icloud_photos_downloader#25]
I have to run 2fa each time my server reboots (e.g. after maintenance). As it's setup as cron job, this is not woking without doing this step manually in advance. Am I missing something ..?

**Comment by ndbroadbent** [comment]
Hi, I haven't seen this happen. I would try to look at the pyicloud library and see where they store the 2FA cookie or token. Or maybe Apple is caching the authentication based on your IP address. To be honest, I'm not sure how it works.

**Comment by hongkongkiwi** [comment]
I'm also seeing the same issue running in Docker.
