### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by BuSHari** [ndbroadbent/icloud_photos_downloader#28]
Hi,

This is a great script!
Is there are a chance that you can make a docker image for that tool? 
I want to use it in my Synology Nas.

Thanks,
Idan

**Comment by eana** [comment]
Hello! 

Check this out: https://github.com/ndbroadbent/icloud_photos_downloader/pull/32

Cheers,
Jonas

**Comment by ndbroadbent** [comment]
Merged!
