### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aphex3k** [ndbroadbent/icloud_photos_downloader#3]
It looks like the line `>>> icloud --username=jappleseed@apple.com` is entered on the python shell, but following the steps outlined in the Readme I receive the following error:
`File "<stdin>", line 1
    icloud --username=jappleseed@apple.com
                                ^
SyntaxError: invalid syntax`

This is for Python version 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609] on linux2

**Comment by ndbroadbent** [comment]
Ah sorry, that's a command-line tool that should be run in bash, not the python shell. I changed the README to use `$` instead of `>>>`, hopefully that makes it more clear
