### ISSUE TITLE
iOS 11 - Photos in HEIC Format

### ISSUE THREAD

**Issue by cutzenfriend** [ndbroadbent/icloud_photos_downloader#34]
Hi, since iOS 11 Photos are save as HEIC Format in iCloud and also downloaded as such.

![ios11-heic](https://user-images.githubusercontent.com/1510611/30542414-9e2bfea0-9c7f-11e7-9bc2-4aea356a8df0.png)

This is completly useless for windows / linux... Maybe convert themautomatically to jpg could be a solution?

**Comment by ndbroadbent** [comment]
Ah, that's a great idea. Pull requests would be very welcome!

I had a quick look to see how easy that would be, and found this python script that can convert HEIC images to PNG:

* https://github.com/ImageMagick/ImageMagick/issues/507#issuecomment-330418013

**Comment by mattwaltbriggs** [comment]
I can't tell you the number of ways this is wrong. So what if iOS 11 supports HEIC?
HEIC has wide ranging applications that go far and beyond iPhone and iPad users.
What about encoding HEIC in ImageMagick too? Uncompressed/raw images could be converted to HEIC, saving space. Wouldn't that be worth quite a lot?
Decoding HEIC is clearly important on non-iOS and macOS systems. Some users might be sent HEIC and not have access to iOS and macOS.

**Comment by ndbroadbent** [comment]
@mattwaltbriggs Sorry what do you mean? Do you want to see an option to both encode and decode HEIC images?

**Comment by mattwaltbriggs** [comment]
Encode and decode HEIC would constitute support for HEIC, so yes. :)
