### ISSUE TITLE
How to get pictures from PhotoStream?

### ISSUE THREAD

**Issue by latonita** [ndbroadbent/icloud_photos_downloader#35]
Hi.
How do I get pictures from photo stream for continuous back up purposes?
Tried to use download_photos, but it tells me 'Downloading 0 original photos'.

thanks.

**Comment by ndbroadbent** [comment]
Hello @latonita, sorry I'm not sure about that. This project is just a small wrapper around [pyicloud](https://github.com/picklepete/pyicloud), so it might be better to ask over there.

**Comment by latonita** [comment]
Thanks. Will check there. 12:54, September 25, 2017, Nathan Broadbent <notifications@github.com>:Hello @latonita, sorry I'm not sure about that. This project is just a small wrapper around pyicloud, so it might be better to ask over there.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.    -- Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail
