### ISSUE TITLE
Downloading 0 original photos

### ISSUE THREAD

**Issue by mariof1** [ndbroadbent/icloud_photos_downloader#38]
Hi, 
I have passed authentication however I am not able to download any photos, no error messages just  the below message shown. I have tried with and without 2fa.

`Looking up all photos...
Downloading 0 original photos and videos to /media/data3/Pictures/icloud/ ...
0it [00:00, ?it/s]
All photos have been downloaded!`

**Comment by ndbroadbent** [comment]
That's strange, sorry I haven't seen that one before. It might be that Apple is taking a while to enable the API access on your account. After the first request it can take a few minutes or hours for things to start working normally.

I tested the script with my own account, and everything is working ok for me:

```
$ ./download_photos.py ./Photos --username ********@********
Two-factor authentication required. Your trusted devices are:
  0: iPhone
  1: SMS to *******03
Which device would you like to use? [0]: 0
Please enter validation code: ****
Great, you're all set up. The script can now be run without user interaction.
You can set up email notifications to receive a notification when two-step authentication expires.
Use --help to view information about SMTP options.
$ ./download_photos.py ./Photos --username ********@********
Looking up all photos...
Downloading 26767 original photos to Photos/ ...
Downloading Photos/2017/09/29/IMG_0691-original.JPG:   0%|         0/26767 [00:03<?, ?it/s]
```

**Comment by ndbroadbent** [comment]
These issues tend to stay open for a really long time when there's no feedback, so please re-open if you still can't get this to work.

**Comment by mdbraber** [comment]
@mariof1 I'm experiencing the exact same issue - were you able to solve this in the end?

**Comment by mariof1** [comment]
Hi @mdbraber,

No sorry I was never able to pass this issue and eventually gave up with the plugin
