### ISSUE TITLE
use an app-specific password for 2 auth

### ISSUE THREAD

**Issue by cutzenfriend** [ndbroadbent/icloud_photos_downloader#42]
What about use an app-specific password when signing in? [https://support.apple.com/en-us/HT204397](https://support.apple.com/en-us/HT204397)

In that case you won't ever have to reauthenticate...

**Comment by ndbroadbent** [comment]
Hi, I think I did try that earlier, but I wasn't able to get it to work. I believe we're using a private API for iCloud, so it didn't support app-specific passwords when I tested it last year. That would be awesome if you could please try that out and let me know if it works now!

**Comment by cutzenfriend** [comment]
Doesn’t work can be closed.
