### ISSUE TITLE
Possible to download only videos?

### ISSUE THREAD

**Issue by fullshutter** [ndbroadbent/icloud_photos_downloader#43]
Hi @ndbroadbent .  Still running like a top.  Thanks again for your help with my other issue.  A quick question - naturally, I forgot to use the "--download-videos" argument.  Once the photos all finish downloading, if I run with the "--download-videos" argument, will it know to get, effectively, only the videos?  I know I read that multiple runs would only get new photos.  But wanted to see if the same applied for videos since, technically, they are new.

Thanks!

**Comment by ndbroadbent** [comment]
Hi, yes `--download-videos` just means that the script will download both images and videos, instead of skipping videos. So it won't download any images again.
