### ISSUE TITLE
Delete after download

### ISSUE THREAD

**Issue by juniortivotyro** [ndbroadbent/icloud_photos_downloader#46]
Is there a way for you to make it automatically delete the photo off of iCloud after it is downloaded? The auto-delete seems to only remove the photos you have automatically deleted.

**Comment by ndbroadbent** [comment]
Hi, I haven't added a way to do that, but after downloading all of your photos, you could try running the script from [this gist](https://gist.github.com/Tatsh/0b5a10a2d25f6c8466290401d2026055):

```
git clone https://github.com/ndbroadbent/icloud_photos_downloader
cd icloud_photos_downloader
curl -sfLO https://gist.github.com/Tatsh/0b5a10a2d25f6c8466290401d2026055/raw/77d23ca0d1448f8e8eb4f208dfcfe84781d98d67/delall-icloud-photos.py
python delall-icloud-photos.py
```

That will delete all the photos and videos from your iCloud account, so be careful with that!
