### ISSUE TITLE
i had to said

### ISSUE THREAD

**Issue by zodman** [ndbroadbent/icloud_photos_downloader#48]
thanks!!!

Where i can invite a coffe ?

**Comment by chrismetcalf** [comment]
Ditto. You should set up a tip jar or something

**Comment by Dave-Evans** [comment]
Ditto ditto. This is fantastic, I can't thank you enough. Why Apple makes it so hard to download photos, I don't know, but you have come through beautifully. Thank you thank you.

**Comment by zodman** [comment]
[]: Implement: https://www.buymeacoffee.com/

**Comment by ndbroadbent** [comment]
Thanks everyone, I'm glad I could help you solve this problem! And thanks for the suggestion @zodman, I've set up a page here - https://www.buymeacoffee.com/ndbroadbent

**Comment by zodman** [comment]
setup your paypal!

**Comment by ndbroadbent** [comment]
Good point! I couldn't figure out how to change it to PayPal, so I switched to a different service. Here's a link that supports PayPal: https://ko-fi.com/ndbroadbent
