### ISSUE TITLE
A few images not downloaded from iCloud

### ISSUE THREAD

**Issue by stefanoco** [ndbroadbent/icloud_photos_downloader#54]
I'm testing this (wonderful) script. Works very well but I noticed an inconsistency on the number of images downloaded from my iCloud account: 827 images on iCloud, 825 images downloaded.

So started to investigate and discovered:

- if I go to "Recently discarded" album (iPhone) and recover one picture, wait for sync to iCloud, the same picture remains in the "Recently discarded" album on iCloud web UI and this script does not get it
- if I go to "Recently discarded" album (iCloud web UI) and recover one picture here, this script gets it

I then reviewed all pictures and found the two missing pictures (present on iCloud, missing locally): they where pictures older than a few months, that for sure I did discard and recover after a few days.

So it seems to me (and I'd like others to comment if already seen):

- when I discard a picture on the iPhone, and recover that picture, the same does not gets immediatly recovered on iCloud
- (perhaps) after the recovery time the picture starts being visible in iCloud but still not downloaded

**Comment by ndbroadbent** [comment]
Thanks again for reporting this issue. It sounds like it might be a problem with the iCloud API. I'm going to close this issue, but hopefully Apple will fix it, or someone will find a way to fix it in the `pyicloud` library that I'm using.
