### ISSUE TITLE
error when : sudo pip install -r requirements.txt on mac

### ISSUE THREAD

**Issue by spike321** [ndbroadbent/icloud_photos_downloader#57]
![image](https://user-images.githubusercontent.com/5576881/37550347-f93dfe8c-2961-11e8-9f79-5e9dce13658c.png)

**Comment by ndbroadbent** [comment]
Hi @spike321, please take a look at this question/answer on StackOverflow: https://stackoverflow.com/a/33245444/304706

`brew install python` might solve the problem

**Comment by spike321** [comment]
do i have to sudo pip install requirements if i'm using OSX? cuz i still keep getting this error even after i download homebrew and brew install python.

**Comment by ndbroadbent** [comment]
Hi @spike321, sorry for the delay. I have to use `sudo pip` on my Mac, but I can't remember how I installed `pip`. There's a few different ways to install Python and pip, and to be honest I'm not sure of the best way. 

But it looks like your error message was "Operation not permitted", so I would just try with sudo: `sudo pip install -r requirements.txt`. Hopefully that fixes it for you!
