### ISSUE TITLE
When running through Docker, 2SA kicks in every time

### ISSUE THREAD

**Issue by johanforssell** [ndbroadbent/icloud_photos_downloader#61]
I'm running the scripts through Docker, exactly as the provided example.

But I'm not getting any two month period before the 2SA kicks in again - it always forces me to fill in the 2SA code. I'm assuming the Dockerization is to blame. Any thoughts?

**Comment by ndbroadbent** [comment]
Hmm, yes that could be a problem with Docker not persisting the authentication. Might need to add a volume to store this outside the container. But I'm not sure where that file is

**Comment by johanforssell** [comment]
I'm fine with supplying the 2SA code when I run the scripts
