### ISSUE TITLE
Bash on Windows

### ISSUE THREAD

**Issue by brentratliff** [ndbroadbent/icloud_photos_downloader#62]
Great project, icloud for Windows is garbage.  Before I jump in do you know if it's compatible with Bash on Windows (Ubuntu) or do I need to use Docker on Win10?  Thanks

**Comment by ndbroadbent** [comment]
Hi @brentratliff, I think it should work fine on Windows, even from the Windows command prompt. I'm using `os.path.join` so the file paths are cross-platform. However, I haven't tested on Windows, so I'd be interested to hear if there's any issues.

**Comment by brentratliff** [comment]
Thanks. I use Windows for various reasons but I'm really more comfortable with the Linux command line.  The Linux subsystem for Windows is one of the main reasons I moved from MacOS after all it's recent bloat.  I'll give it a shot and report back.

**Comment by ndbroadbent** [comment]
Hi @brentratliff, did you ever manage to get it working on Windows? Closing this for now, but would be great to get some feedback if you ran into any problems (or if you didn't!)

**Comment by brentratliff** [comment]
Not yet, I got side tracked by other projects.  When I get to it, I'll be sure to report back.  Thanks.
