### ISSUE TITLE
Question: Preferred interface for downloading Live Images + Videos

### ISSUE THREAD

**Issue by bexelbie** [ndbroadbent/icloud_photos_downloader#69]
I am looking at proposing changes to pyicloud's interface to make it easier to download both the image and movie associated with a live photo.  Input into what that should look like is appreciated:

https://github.com/picklepete/pyicloud/issues/174-

**Comment by ndbroadbent** [comment]
Hi @bexelbie, sorry for the long delay, I haven't been too active on this project (or on `pyicloud`), but once every few months I'll just spend a few hours responding to issues and merging PRs. 

I take a lot of live photos, so I'm definitely interested. Unfortunately I don't actually use this project anymore, and don't have time to work on it, but a PR would be very welcome!
