### ISSUE TITLE
please, add an options for keyring password

### ISSUE THREAD

**Issue by max1404** [ndbroadbent/icloud_photos_downloader#7]
Hello,

if you store your iCloud password in the keyring, you must to set a password for the keyring. When calling "./download_photos.py" you must enter the password of keyring - so it is not possible to run the job regularly via cron.

Please add an option for a keyring password.

Thank you

**Comment by ndbroadbent** [comment]
Hello, sorry, I'm not sure how to do this. Could you please take a look at the [pyicloud](https://github.com/picklepete/pyicloud) library and see if you can help me figure this out?

**Comment by ndbroadbent** [comment]
Actually, please just use the `--username=<username>` and `--password=<password>` options. I don't think it makes much sense to store your iCloud password in the keyring, and then provide your keyring password to unlock your iCloud password. Just provide your iCloud password directly.

I'm going to remove the keyring stuff from the README.
