### ISSUE TITLE
AttributeError: 'PyiCloudService' object has no attribute 'requires_2sa'

### ISSUE THREAD

**Issue by lyashevska** [ndbroadbent/icloud_photos_downloader#71]
./download_photos.py ./mypix --download-videos 
gives the following AttributeError: 'PyiCloudService' object has no attribute 'requires_2sa'

**Comment by andrem123456** [comment]
Within authetication.py you just need to change `if icloud.requires_2sa:` to `if icloud.requires_2fa:`
and it should run fine

**Comment by lyashevska** [comment]
I have changed it, and now I get another error. Not sure if it is related.

```
olga@olga:~/icloud_photos_downloader$ ./download_photos.py mypix --username=xxx --password=xxx --size=original 
Looking up all photos...
Traceback (most recent call last):
  File "/home/olga/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/olga/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/olga/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known


```

**Comment by ndbroadbent** [comment]
Hello,

I'm using a forked version of `pyicloud` with the `requires_2sa`, which you need to install. I've copied the library into this project to make it easier. Please update `icloud_photos_downloader` with `git pull`, then uninstall your current version of `pyicloud`:

```
sudo pip uninstall pyicloud
```

After that, install the dependencies again:

```
sudo pip install -r requirements.txt
```

This will install the correct version of `pyicloud`.

@lyashevska Sorry I'm not sure about the "Name or service not known" error, but sounds like an internet or DNS issue. Hopefully you were able to get it to work!
