### ISSUE TITLE
Module import error straight off the bat

### ISSUE THREAD

**Issue by aaron-michaux** [ndbroadbent/icloud_photos_downloader#73]
Module import error (after pip install)

```
user@host > ./download_photos.py --help
Traceback (most recent call last):
  File "./download_photos.py", line 3, in <module>
    import click
ImportError: No module named click
```

Ubuntu 16.04

What version of python is this supposed to be using?

**Comment by DJBenson** [comment]
Did you install the requirements?

`sudo pip install -r requirements.txt`

I got this error and realised I hadn't installed the dependencies using the above step.

I also got an error about my version of "six" being too new so I ran sudo pip install six==??? where ??? is the version number reported by the error.

**Comment by a42887** [comment]
Same issue here.  Definitely installed the requirements.  Any ideas?

**Comment by ndbroadbent** [comment]
Thanks @a42887, glad you figured it out! Yeah Python 2 / 3 issues can be really tricky. Sometimes there's also `pip` for Python 2, and `pip3` for Python 3.

I keep seeing people experiencing these Python and pip errors, and would like to figure out a better solution. Would be great if everything could be self-contained and isolated so I don't have to worry about versions or dependencies.
