### ISSUE TITLE
How to install use this code on Mac OS

### ISSUE THREAD

**Issue by oct-test** [ndbroadbent/icloud_photos_downloader#77]
I want to try this plug-in on my Mac Mini (macOS sierra 10.13.5) and I am trying to install the requirements using command "sudo pip install -r requirements.txt". The command generates following error:

Could not find a version that satisfies the requirement schema (from -r requirements.txt (line 2)) (from versions: )
  No matching distribution found for schema (from -r requirements.txt (line 2))

How can I fix this issue? Will this plug-in work with iOS 11.4?
Thank you.

**Comment by ndbroadbent** [comment]
Hi @oct-test, sorry for the delay. I've just updated the `requirements.txt` file to include specific versions that are working for me. Please `git pull` and try again, and let me know if that fixes it for you

**Comment by oct-test** [comment]
Hello again. I tried the latest **requirements.txt** and still getting the same error on my Mac machine. I am able to run the tool on my Windows machine.

I am trying port the iCloud's 2FA login process for the Android platform. I am getting following response when validating the verification code sent to the trusted device:

{"success":false,"error":"Missing X-APPLE-WEBAUTH-HSA-LOGIN cookie"}

Can you help me understanding the cause for this issue and how to possibly fix this issue? I would appreciate any suggestions and thoughts on this topic. Thank you.
