### ISSUE TITLE
Error: Got unexpected extra arguments (\ \ \)

### ISSUE THREAD

**Issue by JoshWhite** [ndbroadbent/icloud_photos_downloader#81]
Hey, 

I'm a newb with Python, so sorry if some of this is obvious.

I'm not sure if I should be using Python 2.7 or 3.6. I got errors with 3.6, so assumed I would need 2.7.

After installing, I ran the example script with my credentials. 

I got this error:
`Error: Invalid value for "directory": Path "./Photos" does not exist.`

After creating said dir, I got the error:
`Error: Got unexpected extra arguments (\ \ \)`

I'm pretty lost at this point!
Any help appreciated :)

Edit:
I'm running on a windows machine, if that helps

**Comment by ndbroadbent** [comment]
Hi @JoshWhite, sorry that you're experiencing these issues! It's supposed to work on both Python 2 and 3, so I'll investigate those issues. 

I've fixed that `./Photos` error, making sure that the folder exists when you clone the git repo.

I've never seen `Error: Got unexpected extra arguments (\ \ \)` (although I haven't tested on Windows for quite some time.) Could you please post the full output from the script, so I can see the location of the error?

**Comment by ndbroadbent** [comment]
Hmm ok, that's strange! I can't think of anything that would cause no photos or videos to be downloaded. Did you see some information in the progress bar about files being downloaded? (e.g. `IMG_*****`?)

**Comment by JoshWhite** [comment]
I opened a separate issue #89. I'll close this, as it was just a case of poor cmd knowledge.
