### ISSUE TITLE
Parallel downloads

### ISSUE THREAD

**Issue by ndbroadbent** [ndbroadbent/icloud_photos_downloader#91]
If Apple is limiting the download speed for each photo, then it could make sense to download 3-5 items in parallel. This should be a new CLI option, e.g. `--threads 3`

Note: The `tqdm` progress will support [nested progress bars for each thread](https://github.com/tqdm/tqdm#nested-progress-bars).

**Comment by AndreyNikiforov** [comment]
@ndbroadbent is there any reference that Apple is throttling download speeds by connection? 

If not, then limiting factor is inet connection speed and adding parallel downloading introduces complexity without any noticeable benefit.

**Comment by menkej** [comment]
This is already there, right? Is this issue still current @ndbroadbent ?

**Comment by ndbroadbent** [comment]
> is there any reference that Apple is throttling download speeds by connection?

Sorry I can't remember if I had any reference for this, I think it might have just been a guess

> This is already there, right? Is this issue still current @ndbroadbent?

Right, this can be closed! Thanks!
