### ISSUE TITLE
Photos with invalid date raises exception

### ISSUE THREAD

**Issue by jetthe** [ndbroadbent/icloud_photos_downloader#92]
iOS hasn't always been the best at handling timestamps for photos and sometimes you end up with pictures on iCloud with invalid dates, showing as as "1 July 2743924" or similar in the iOS Photo app.
This is currently not handled well when downloading the file and an exception is raised:
`  File ".local/lib/python2.7/site-packages/icloudpd/base.py", line 266, in main
 created_date = photo.created.astimezone(get_localzone())

ValueError: astimezone() cannot be applied to a naive datetime
`

It can be a real hassle to find the picture in question so some kind of automated workaround would be nice. Just catching the exception and either skipping the file or setting the current timestamp would be enough.

The date/time looks OK when viewing the EXIF info for the file so I'm not sure what's causing the original issue and I'm not able to reproduce it, perhaps the cause is a bug in some earlier version of iOS (the files causing me trouble were downloaded in 2016).

**Comment by ndbroadbent** [comment]
Hi @jetthe, I've just pushed `1.0.6` which should handle this error during the time zone conversion. Please let me know if that fixes the issue for you, or if there are any new crashes

**Comment by ndbroadbent** [comment]
Thanks for letting me know about this issue, and I believe it should be fixed in the latest version. Closing for now!
