### ISSUE TITLE
2FA authentication not remembered after reboot

### ISSUE THREAD

**Issue by boredazfcuk** [ndbroadbent/icloud_photos_downloader#96]
Hi,
I've installed this script within a container which I shutdown and backup each night. As soon as I reboot the container I have to re-authenticate via 2FA.

I've noticed that it saves the cookie session info in /tmp/pyicloud/

Could this not be stored in my user profile so that it is remembered between reboots instead?

Thanks

**Comment by ndbroadbent** [comment]
Hey that's a great idea! I've added the `--cookie-directory` option and made the default `~/.pyicloud`. On MacOS it always ends up in a weird auto-generated folder like `/var/tmp/.../.../pyicloud`, so this is way better.

You can update to `1.3.0` with `pip install icloudpd==1.3.0`
